# Generated by Django 6.0 on 2025-12-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_final_score_enrollment_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('teacher', '教師'), ('student', '學生')], default='student', max_length=10),
        ),
    ]
