# Generated by Django 5.2.7 on 2025-11-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_course_id_alter_course_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='final_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='midterm_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.CharField(max_length=50),
        ),
    ]
